export const SELECT_CONTEXT = "SELECT_CONTEXT"
export const SET_CHAPID = "SET_CHAPID"
export const ADD_FAV = "ADD_FAV"
export const REMOVE_FAV = "REMOVE_FAV"
export const ADD_NOTE = "ADD_NOTE"
export const REMOVE_NOTE = "REMOVE_NOTE"